name: Development build

on:
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
    
    runs-on: macos-14


    steps:
      
      - name: Remove work folders
        run: |
          echo "before"
          ls -lah ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./
          
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout repository submodules
        run: git submodule update --init --recursive
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install Rosetta
        run: |
          /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      - name: Install dpkg
        run: |
          brew install dpkg fakeroot || true # only if you're building debs
  
      - name: Install GNU Make (gmake)
        run: brew install make
      - name: Install JDK 8
        run: |
          brew install --cask temurin@8
          java -version
      - name: Install ldid
        run: brew install ldid

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin

          export PATH=/opt/homebrew/bin:$PATH
          
          export CFLAGS="-O0 -g -fno-inline"
          export CXXFLAGS="-O0 -g -fno-inline"

          arch -x86_64 gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          
         
      - name: Upload regular ipa
        uses: actions/upload-artifact@main
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa
