name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Build iOS IPA
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-14
    defaults:
      run:
        shell: bash

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Put Homebrew arm64 executables on PATH
      - name: Add Homebrew bin to PATH
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      # 3. Install  deps
      - name: Install dependencies
        run: |
          brew install make dpkg fakeroot ldid || true
       

      # 4. Setup Java (for any dpkg/java tooling)
      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '1.8.x'


      # 5. Clean build artifacts
      - name: Clean previous build
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          mkdir -p artifacts

      # 6. Build IPA
      - name: Build iOS package
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export SLIMMED=1
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}

      # 7. Upload the IPA
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa
