name: Development build1

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Build iOS IPA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    defaults:
      run:
        shell: bash

    steps:
      # 1. Checkout source code (including submodules)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install native dependencies via apt
      - name: Install native deps
        run: |
          sudo apt-get update
          sudo apt-get install -y make dpkg fakeroot ldid

      # 3. Set up Java 1.8 (Temurin)
      - name: Set up Java 1.8 (Temurin)
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # 4. Verify Java and export env vars
      - name: Verify Java & configure JAVA_HOME
        run: |
          java -version
          echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV
          echo "PATH=${{ steps.setup-java.outputs.java-home }}/bin:$PATH" >> $GITHUB_ENV

      # 5. Clean previous build artifacts
      - name: Clean previous build
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          mkdir -p artifacts

      # 6. Build the iOS IPA
      - name: Build iOS package
        run: |
          # ensure any custom PATH changes are applied
          export PATH=${{ steps.setup-java.outputs.java-home }}/bin:$PATH
          # parallel make for speed
          gmake -j$(nproc) dsym package PLATFORM=${{ matrix.platform }}

      # 7. Upload the IPA artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa
